"""Utility methods for the node sort algorithm in 2D truss optimization problems."""

from __future__ import annotations

from itertools import chain
from itertools import combinations
from typing import TYPE_CHECKING

from engibench.problems.truss2d.model import utils

if TYPE_CHECKING:
    from engibench.problems.truss2d.model.conditions import Conditions

ABOVE_COUNT_LIMIT = 2
BELOW_COUNT_LIMIT = 2



def search_algorithm(conditions: Conditions, load_idx: int = 0) -> list[list[int]]:
    """Returns a set of designs generated using the NodeSort algorithm.

    Args:
        conditions (Conditions): The problem conditions.
        load_idx (int): The index of the load condition to consider.

    Returns:
        npt.NDArray: An array of bit-list designs generated by the NodeSort algorithm.
    """
    nodes = conditions.nodes


    all_node_idx = list(range(len(nodes)))
    fixed_node_idx = utils.get_fully_fixed_nodes(conditions)
    load_node_idx = utils.get_load_nodes(conditions.load_conds[load_idx])

    static_nodes = fixed_node_idx + load_node_idx
    free_nodes = [x for x in all_node_idx if x not in static_nodes]

    # Get all combinations of fixed nodes
    fixed_nodes_pwr_set = list(power_set(fixed_node_idx))
    static_nodes_comb_feasible = [
        list(fixed_nodes_comb) + load_node_idx
        for fixed_nodes_comb in fixed_nodes_pwr_set
        if len(fixed_nodes_comb) > 1
    ]

    # Get all combinations of free nodes
    free_nodes_pwr_set = list(power_set(free_nodes))

    # Iterate over all combinations of free nodes, and generate a design for each with NodeSort
    designs = []
    for static_nodes_comb in static_nodes_comb_feasible:
        for free_node_comb in free_nodes_pwr_set:
            node_comb = list(free_node_comb) + static_nodes_comb
            node_comb = list(set(node_comb))
            nodes_new = [nodes[idx] for idx in node_comb]

            # Get NodeSort design and convert
            edges_new = node_sort(nodes_new)
            _, _, node_idx_pairs, _ = utils.convert(conditions, edges_new)

            # Remove members connecting fixed nodes
            node_idx_pairs_fixed = remove_members_connecting_fixed(node_idx_pairs, fixed_node_idx)
            bit_list, _, node_idx_pairs, _ = utils.convert(conditions, node_idx_pairs_fixed)

            # Append design to design set
            designs.append(bit_list)

    return designs

def power_set(iterable: list) -> chain:
    """Returns an iterator over all subsets (the power set) of the iterable.

    Args:
        iterable (list): The input list to generate the power set from.

    Returns:
        chain: An iterator over all subsets of the input list.
    """
    s = list(iterable)
    # Generates combinations for all possible lengths r from 0 to len(s)
    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))

def node_sort( # noqa: PLR0912 C901
        nodes: list[tuple]) -> list[tuple]:
    """Implements the NodeSort truss design algorithm.

    Args:
        nodes (list of tuple): A list of nodes, where each node is an (x, y) tuple.

    Returns:
        list of tuple: A list of edges representing the truss design.
                       ((x1, y1), (x2, y2))
    """
    # 1. Sort nodes ascending over x, if equal compare over y
    sorted_nodes = sorted(nodes)
    n = len(sorted_nodes)

    edges = []

    # 2. Point to first node i = 0
    # 3. Loop while i < (n_i - 1)
    # Correction: The loop must process the second-to-last node
    # to ensure the final segment is connected.
    # range(n-1) goes from 0 to n-2.
    for i in range(n - 1):
        node_i = sorted_nodes[i]

        # We start checking from the very next node
        next_node_index = i + 1
        if next_node_index >= n:
            break

        node_next = sorted_nodes[next_node_index]

        targets = []

        # Determine if we are in Case A (Next node is equal/lower) or B (Next node is higher)
        # Note: The prompt says "node_i.y >= node_{i+1}.y" for A
        if node_i[1] >= node_next[1]:
            # --- CASE A: Ascending Search ---
            above_count = 0

            for j in range(i + 1, n):
                candidate = sorted_nodes[j]

                # Check Break Criterion (a): Ordering
                # We compare current candidate with the PREVIOUSLY collected target
                # to ensure the sequence of targets is ascending over y.
                if targets:
                    prev_target = targets[-1]
                    # If candidate drops below the previous target, ordering is broken
                    if candidate[1] < prev_target[1]:
                        break

                        # Check Break Criterion (b): Count of nodes above node_i
                # We collect the node first, then check if we should stop future searches.
                is_above = candidate[1] > node_i[1]

                if is_above:
                    above_count += 1

                # Add the candidate to the truss
                targets.append(candidate)

                # If this was the second node above, we break *after* adding it.
                # This ensures we capture the closing edge of the triangle.
                if above_count == ABOVE_COUNT_LIMIT:
                    break

        else:
            # --- CASE B: Descending Search ---
            below_count = 0

            for j in range(i + 1, n):
                candidate = sorted_nodes[j]

                # Check Break Criterion (a): Ordering (Descending)
                if targets:
                    prev_target = targets[-1]
                    # If candidate rises above the previous target, ordering is broken
                    if candidate[1] > prev_target[1]:
                        break

                # Check Break Criterion (b): Count of nodes below node_i
                is_below = candidate[1] < node_i[1]

                if is_below:
                    below_count += 1

                targets.append(candidate)

                if below_count == BELOW_COUNT_LIMIT:
                    break

        # C. Define trusses
        edges.extend((node_i, target) for target in targets)


    return edges

def remove_members_connecting_fixed(node_idx_pairs: list[tuple[int, int]], fixed_nodes_idx: list[int]) -> list[tuple[int, int]]:
    """Removes members that connect two fixed nodes.

    Args:
        node_idx_pairs (list of tuples): List of node index pairs representing truss members.
        fixed_nodes_idx (list of int): List of indices of fixed nodes.

    Returns:
        node_idx_pairs_new (list of tuples): Filtered list of node index pairs with members connecting fixed nodes removed.
    """
    node_idx_pairs_new = []
    for node_idx_pair in node_idx_pairs:
        node1, node2 = node_idx_pair
        if node1 in fixed_nodes_idx and node2 in fixed_nodes_idx:
            continue
        node_idx_pairs_new.append(node_idx_pair)
    return node_idx_pairs_new
